"""
rox_sniffer.py — mitmproxy addon to capture and decode RöX game traffic.

This script runs as a mitmproxy addon and intercepts all HTTP/HTTPS traffic
from the RöX game process, saving decoded requests and responses so we can
understand the game's network protocol.

HOW TO RUN
----------
1. Start the proxy (intercept mode):
       .venv/bin/mitmdump -s rox_sniffer.py --listen-port 8080 --set block_global=false

2. Set macOS system proxy:
       networksetup -setwebproxy Wi-Fi 127.0.0.1 8080
       networksetup -setsecurewebproxy Wi-Fi 127.0.0.1 8080

3. Trust mitmproxy's CA certificate (one-time):
       open ~/.mitmproxy/mitmproxy-ca-cert.pem
       # In Keychain: mark as "Always Trust"

4. Play RöX normally — traffic will be logged to rox_traffic/

5. Restore proxy when done:
       networksetup -setwebproxystate Wi-Fi off
       networksetup -setsecurewebproxystate Wi-Fi off

OUTPUT
------
rox_traffic/
    all_requests.jsonl   — Every request/response as JSON lines
    game_server.jsonl    — Only traffic to the game server IPs
    DISCOVERED.md        — Auto-updated summary of discovered endpoints

KNOWN GAME SERVER IPs (from lsof while game running):
    140.248.130.73       — Primary game server (HTTPS)
    166.146.160.34       — Google Cloud game server (port 9200, likely WebSocket)
    *.akamaitechnologies.com — CDN (asset bundles — less interesting)

NOTE ON CERTIFICATE PINNING
----------------------------
If RöX uses certificate pinning, you'll see SSL errors and no game traffic.
Check rox_traffic/ssl_errors.log — if it grows, pinning is active.
Workaround options:
  1. Use mitmproxy's --ssl-insecure flag (tells mitmproxy to ignore upstream errors)
  2. The game may only pin certain hosts — CDN traffic may still be visible
  3. Check rox_traffic/game_server.jsonl for any successful captures
"""

from __future__ import annotations

import json
import os
import re
import time
from datetime import datetime
from typing import Optional

from mitmproxy import ctx, http
from mitmproxy.websocket import WebSocketMessage


# ── Output directory ──────────────────────────────────────────────────────────
OUT_DIR = os.path.join(os.path.dirname(__file__), "rox_traffic")
os.makedirs(OUT_DIR, exist_ok=True)

ALL_LOG       = os.path.join(OUT_DIR, "all_requests.jsonl")
GAME_LOG      = os.path.join(OUT_DIR, "game_server.jsonl")
WS_LOG        = os.path.join(OUT_DIR, "websocket.jsonl")
SSL_ERROR_LOG = os.path.join(OUT_DIR, "ssl_errors.log")
SUMMARY_FILE  = os.path.join(OUT_DIR, "DISCOVERED.md")

# Known game server IPs / hostnames (from lsof output while game running)
GAME_HOSTS = {
    "140.248.130.73",
    "166.146.160.34",
    "166.146.160.34.bc.googleusercontent.com",
}

# CDN / analytics — less interesting but still logged
CDN_PATTERNS = re.compile(
    r'akamaitechnologies|akamaized|bytedance|bdstatic|toutiao|sgsnssdk|tiktok',
    re.IGNORECASE
)

# ── Endpoint discovery tracker ────────────────────────────────────────────────
_discovered: dict[str, dict] = {}   # host → {paths: set, methods: set, count: int}


def _is_game_host(host: str) -> bool:
    return host in GAME_HOSTS or host.endswith(tuple(GAME_HOSTS))


def _safe_decode(data: bytes, max_bytes: int = 8192) -> str:
    """Try UTF-8, then latin-1, then hex dump for binary."""
    if len(data) > max_bytes:
        data = data[:max_bytes]
    try:
        text = data.decode("utf-8")
        # Try to pretty-print JSON
        try:
            obj = json.loads(text)
            return json.dumps(obj, indent=2, ensure_ascii=False)
        except Exception:
            return text
    except UnicodeDecodeError:
        try:
            return data.decode("latin-1")
        except Exception:
            return data.hex()


def _log(path: str, record: dict) -> None:
    with open(path, "a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


def _update_discovered(host: str, path: str, method: str,
                        status: int, content_type: str) -> None:
    if host not in _discovered:
        _discovered[host] = {"paths": set(), "methods": set(), "count": 0,
                              "status_codes": set()}
    info = _discovered[host]
    info["paths"].add(path)
    info["methods"].add(method)
    info["status_codes"].add(status)
    info["count"] += 1
    _write_summary()


def _write_summary() -> None:
    lines = [
        "# RöX Network Traffic — Discovered Endpoints\n",
        f"*Auto-generated by rox_sniffer.py — last updated {datetime.now():%Y-%m-%d %H:%M:%S}*\n\n",
    ]
    for host in sorted(_discovered):
        info = _discovered[host]
        tag = "🎮 GAME SERVER" if _is_game_host(host) else "📦 OTHER"
        lines.append(f"## {tag} `{host}`\n")
        lines.append(f"- **Requests captured:** {info['count']}\n")
        lines.append(f"- **Methods:** {', '.join(sorted(info['methods']))}\n")
        lines.append(f"- **Status codes:** {', '.join(str(s) for s in sorted(info['status_codes']))}\n")
        lines.append("- **Paths:**\n")
        for p in sorted(info["paths"])[:50]:
            lines.append(f"  - `{p}`\n")
        lines.append("\n")
    with open(SUMMARY_FILE, "w", encoding="utf-8") as f:
        f.writelines(lines)


# ── mitmproxy addon class ─────────────────────────────────────────────────────

class RoXSniffer:
    """mitmproxy addon that captures and logs RöX game traffic."""

    def __init__(self) -> None:
        try:
            ctx.log.info("🎮 RoXSniffer started — logging to rox_traffic/")
            ctx.log.info(f"   Watching game hosts: {GAME_HOSTS}")
        except AttributeError:
            pass  # ctx.log only available inside mitmproxy runtime

    def request(self, flow: http.HTTPFlow) -> None:
        """Log outgoing requests."""
        host = flow.request.host
        # Skip localhost / mitmproxy internals
        if host in ("localhost", "127.0.0.1", "mitm.it"):
            return

        # Annotate the flow so we can identify game traffic in response()
        flow.metadata["is_game"] = _is_game_host(host)
        flow.metadata["is_cdn"]  = bool(CDN_PATTERNS.search(host))

        if flow.metadata["is_game"]:
            try:
                ctx.log.info(
                    f"  → [{flow.request.method}] https://{host}{flow.request.path[:80]}"
                )
            except AttributeError:
                pass

    def response(self, flow: http.HTTPFlow) -> None:
        """Log responses with bodies."""
        if flow.response is None:
            return

        host    = flow.request.host
        path    = flow.request.path
        method  = flow.request.method
        status  = flow.response.status_code
        ct      = flow.response.headers.get("content-type", "")

        # Build record
        record = {
            "ts":          time.time(),
            "time":        datetime.now().isoformat(),
            "host":        host,
            "port":        flow.request.port,
            "method":      method,
            "path":        path,
            "status":      status,
            "content_type": ct,
            "req_headers": dict(flow.request.headers),
            "req_body":    _safe_decode(flow.request.get_content() or b""),
            "resp_body":   _safe_decode(flow.response.get_content() or b""),
        }

        # Log everything
        _log(ALL_LOG, record)

        # Separate file for game server traffic
        if flow.metadata.get("is_game"):
            _log(GAME_LOG, record)
            try:
                ctx.log.info(
                    f"  ← [{status}] {host}{path[:60]}  ({ct[:40]})"
                )
            except AttributeError:
                pass

        # Update discovery summary
        _update_discovered(host, path, method, status, ct)

    def websocket_message(self, flow: http.HTTPFlow) -> None:
        """Capture WebSocket frames — likely real-time game state updates."""
        assert flow.websocket is not None
        msg = flow.websocket.messages[-1]
        host = flow.request.host

        record = {
            "ts":        time.time(),
            "time":      datetime.now().isoformat(),
            "host":      host,
            "path":      flow.request.path,
            "direction": "client→server" if msg.from_client else "server→client",
            "type":      "text" if msg.type.name == "TEXT" else "binary",
            "content":   _safe_decode(msg.content if isinstance(msg.content, bytes)
                                      else msg.content.encode()),
        }

        _log(WS_LOG, record)

        if _is_game_host(host) or True:   # log all WS for now
            try:
                ctx.log.info(
                    f"  WS {'→' if msg.from_client else '←'} {host}: "
                    f"{str(record['content'])[:100]}"
                )
            except AttributeError:
                pass

    def tls_failed_client(self, data) -> None:  # type: ignore[override]
        """Log TLS/certificate pinning failures."""
        msg = f"{datetime.now().isoformat()}  TLS client error: {data}\n"
        with open(SSL_ERROR_LOG, "a") as f:
            f.write(msg)
        try:
            ctx.log.warn(f"TLS error (possible cert pinning): {data}")
        except AttributeError:
            pass

    def tls_failed_server(self, data) -> None:  # type: ignore[override]
        msg = f"{datetime.now().isoformat()}  TLS server error: {data}\n"
        with open(SSL_ERROR_LOG, "a") as f:
            f.write(msg)


# mitmproxy entry point
addons = [RoXSniffer()]
